[package]
name = "rdrive"
version = "0.1.0"
authors = ["Benjamin Sproule <benjamin@benjaminsproule.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.28"
futures = "0.3.28"
glob = "0.3.1"
google-drive3 = "*"
hyper = "^0.14.27"
hyper-rustls = "^0.24.1"
log4rs = { version = "1.2.0", features = ["file_appender"] }
log = "0.4"
mime = "0.3.17"
mime_guess = "2.0.4"
regex = "1"
rusqlite = "0.29.0"
serde = { version = "^1.0.188", features = ["derive"] }
serde_json = "^1.0.105"
tokio = { version = "1.32.0", features = ["full"] }
yup-oauth2 = "^8.3"
serial_test = "0.8.0"
