[package]
name = "rdrive"
version = "0.1.0"
authors = ["Benjamin Sproule <benjamin@benjaminsproule.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.13"
futures = "0.3.5"
glob = "0.3.0"
google-drive3 = "*"
hyper = "^0.10"
hyper-rustls = "^0.6"
log4rs = { version = "0.12.0", features = ["file_appender"] }
log = "0.4"
mime = "0.3.16"
mime_guess = "2.0.3"
regex = "1"
rusqlite = "0.23.1"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
tokio = { version = "1.13.1", features = ["full"] }
yup-oauth2 = "^1.0"
serial_test = "0.5.1"
