name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install required libs for build
        run: sudo apt-get install -y libgtk-4-dev libadwaita-1-dev
      - name: Run formatting check
        run: cargo fmt --all -- --check
      - name: Run lint
        run: cargo clippy --all-features --all-targets
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
